### PR TITLE
Decouple internal vs. external naming and improving variable naming consistency

### PR DESCRIPTION
**Pull request by scheibo**
- make all the field names on state follow a consistent camelCase schema\*
- use a separate `display` function to enable us to display pretty strings to humans (a followup PR will Konami-fy this mapping and all the messages)
- fix `Mill`'s action name and minor copy+paste discrepancies in the lambda functions touched by this commit

\* **This is a breaking change - this PR contains no migration logic so existing state representations will break**

### CODE REVIEW

**Comment by acpennington** [comment]
I think there might be somewhere in the styles where the ST constant is (implicitly) referenced and changing it might somehow mess up the styles. Of course this is my bad since I didn't really make this obvious. I'll have to look things over and make sure that the styles didn't get inadvertently messed up. Otherwise, this is all good.

**Comment by scheibo** [comment]
I noticed those, but it was actually not using the constant but instead the literal string `"ST"`. But since you mentioned it I went back and verified and in the process renamed everything else to be consistent as well (originally didn't care as much because it wasn't going to be breaking and I wanted to make this change as small as possible to limit risk).

Still definitely worth running this yourself to make sure it works, especially since I am limited in my ability to test given I can't verify the Lambdas

**Comment by acpennington** [comment]
When I tested your changes and started a new PVP game, everything crashed. Can you try it yourself and let me know what's up?

**Comment by scheibo** [comment]
> This is a breaking change - this PR contains no migration logic so existing state representations will break

I kind of already called that out and also [explained that to you in PMs](https://discord.com/channels/@me/864532918957375509/869417093198663850)? I also can't test it because it depends on the Lambdas being deployed

**Comment by acpennington** [comment]
Alright, I'll have to test each of the changes individually today. I didn't have much time last time to figure out what was causing the issue.

**Pull request merged**
