### PR TITLE
Konami-fy names and messages

### PR DESCRIPTION
**Pull request by scheibo**
Per https://yugioh.fandom.com/wiki/Banish#History, "banished cards" is the current language for what we colloquially call that "Banished Zone", though if we wanted to be more true to history these might instead be called "removed from play cards". I chose to go with "banished cards" as its a) technically now official and b) probably most familiar to plays c) less wordy than "removed from play cards"

### CODE REVIEW

**Comment by acpennington** [comment]
Most of this looks good. Two changes that I don't want to go with.
- I put RANDOMLY in all caps because I want it to stand out to the reader to distinguish from a player discarding a card of their own choice. If it does not stand out, its far too easy for players to try to cheat their opponent if they are not paying close attention to the chat. Doesn't necessarily have to be all caps, but either bold or a different color or something.
- The word "Nobleman" was intentionally left vague because there are both Nobleman of Crossout and Nobleman of Extermination doing the same kind of effect. Alternative would be to just have two different messages for each, I suppose.

**Comment by scheibo** [comment]
> Most of this looks good. Two changes that I don't want to go with.
> 
> * I put RANDOMLY in all caps because I want it to stand out to the reader to distinguish from a player discarding a card of their own choice. If it does not stand out, its far too easy for players to try to cheat their opponent if they are not paying close attention to the chat. Doesn't necessarily have to be all caps, but either bold or a different color or something.

OK, switched to bold.

> * The word "Nobleman" was intentionally left vague because there are both Nobleman of Crossout and Nobleman of Extermination doing the same kind of effect. Alternate would be to just have two different messages for each, I suppose.

I've changed this to use the `variant` string. However, I think Nobleman handling in general needs to be drastically overhauled, as is it involves a lot of hardcoding and seems very hacky.

**Comment by acpennington** [comment]
As far as I know, the two Noblemans really are a special case, so I don't think hardcoding is a big deal. It's possible that the code may become a little less hacky after I complete #178 but we'll have to see.

**Comment by scheibo** [comment]
OK, this should be good to go. Lambda's need to be redeployed for most of it to take effect, but it still works without that.

**Pull request merged**
